include::./.asciidoctor/.asciidoctorconfig[]

== Глава 12. Наследование: хорошо или плохо.

.http://propella.sakura.ne.jp/earlyHistoryST/EarlyHistoryST.html[The Early History Of Smalltalk]
[quote, Alan C. Kay]
Мы начали продвигать наследование, что бы начинающие программисты могли пользоваться каркасами, спроектировать которые под силу только опытным специалистам.

Мы начнём с вопроса о наследовании встроенным типам.

=== Сложность наследования встроенным типам

CAUTION: Прямое наследование таким встроенным типам, как `dict`, `list`, `str`, чревато ошибками, потом что встроенные методы, как правило, игнорируют написанные пользователем переопределенный метод. Вместо создания подклассов встроенных объектов наследуйте свои классы от классов в модуле `collections` https://docs.python.org/3/library/collections.html[ — Container datatypes] -- `UserDict`, `UserList` и `UserString`, который специально предназначены для беспроблемного наследования.

=== Жизнь с множественным наследованием

 1. Отличайте наследование интерфейса от наследования реализации.
    - Наследование _интерфейса_ создает подтип, подразумевая связь *"является"*;
    - Наследование _реализации_ позволяет избежать *дублирования кода*;

 2. Определяйте интерфейсы явно при помощи ABC
    - При помощи явного объявления наследования `abc.ABC`

 3. Используйте примеси для повторного использования кода.
    - Примесь не определяет нового типа, просто создает контейнер для общеполезных методов.

 4. Явно определяйте примеси с помощью наименования.
    - При помощи суффикса Mixin

 5. ABC тоже может быть примесью, обратное неверно

 6. Не наследуйте сразу нескольким конкретным классам
    - class MyClass(Alpha, Beta, Gamma):
    - Alpha -- конкретный класс
    - Beta, Gamma -- примеси или ABC

 7. Предоставляйте пользователям агрегаторные класс.
    - Это классы, которые строятся путём наследования примесями и не добавляет никакой структуры или поведения.

 8. Предпочитайте композицию наследованию класса.


===

