include::./.asciidoctor/.asciidoctorconfig[]

== Глава 11. Интерфейсы: от протоколов до абстрактных классов.

CAUTION: ABC, подобно дескрипторам и метаклассам, предназначены для разработки каркасов. Поэтому лишь малая часть пишущих на Python может создавать ABC, не налагая ненужных ограничений на своих коллег.

=== Интерфейсы и протоколы в культуре Python

NOTE: *_Интерфейс_* -- подмножество открытых методов объекта, которое позволяет ему играть определённую роль в системе.

NOTE: *_Протоколы_* -- это интерфейсы, но поскольку они не формализованы -- определены лишь путём документирования и соглашения -- то не могут быть строго поддержаны как формальные интерфейсы

Одним из самых фундаментальных интерфейсов в Python -- протокол последовательности.

=== Python в поисках следов последовательностей.

Интерпретатор Python прилагает все усилия, стараясь обработать объекты, представляющие самую минимальную реализацию протокола последовательностей.

Sequence -- Последовательность

.UML-диаграмма абстрактного базового класса *Sequence* (последовательность)
[ditaa]
----

Формальное опредление интерфейса Sequnce в виде ABC

 +--------------\           +-----------------\
 | Container    |<----------| Sequence        |
 +--------------+           +-----------------+
 | __contains__ |           |   __getitem__   |
 \--------------+           |   __contains__  |
                            |   __iter__      |
 +--------------\           |   __reversed__  |
 | Iterable     |<----------|   index         |
 +--------------+           |   count         |
 | __iter__     |           \-----------------+
 \--------------+                    |
                                     |
 +--------------\                    |
 | Sized        |<-------------------/
 +--------------+
 | __len__      |
 \--------------+
----

.Частичная реализация протокола последовательности: метода `\\__getitem__` достаточно для доступа к элементам, итерирования и реализации оператора `in`
[source, doctest]
----
>>> class Foo:
...     def __getitem__(self, pos):
...         return range(0, 30, 10)[pos]
...
>>> f = Foo()
>>> f[1]
10
>>> for i in f: print(i)
0
10
20
>>> 20 in f
True
>>> 15 in f
False
----

Метода `\\__iter__` в классе *Foo* нет, однако его экземпляры являются итерируемыми объектами, потому что даже в случае отсутствия `\\__iter__` Python, обнаружив метод `\\__getitem__`, пытается обойти объект, вызывая этот метод, с целочисленными индексами, начиная с 0. Поскольку Python достаточно умён, что бы обойти объект Foo, он может также реализовать оператор `in`, даже если в классе нет метода `\\__contains__`: для этого достаточно просто обойти объект в поисках элемента.

=== Monkey patching или партизанское латание.

[source, doctest]
----
>>> from deck import FrenchDeck         # Пример партизанского латания
>>> def set_card(deck, position, card): # метод это всего лишь функция
...     deck._cards[position] = card    # Данная функция знает об deck._cards
...
>>> FrenchDeck.__setitem__ = set_card   # Латаем функцию к специальному методу
>>> deck = FrenchDeck()
>>> from random import shuffle
>>> shuffle(deck)                   # Теперь наша колода поддерживает перетасовку
>>> deck[:5]
[Card(rank='J', suit='крести'), Card(rank='6', suit='крести'), Card(rank='8', suit='черви'), Card(rank='2', suit='пики'), Card(rank='J', suit='буби')]
----

Как пример динамической типизации можно подчеркнуть протокол `random.shuffle`. Ему всё равно какой аргумент ему передан, лишь бы он мог реализовать метод изменения последовательности.

NOTE: Вызов `isinstance(obj, cls)` приемлем, при условии, что `cls` -- абстрактный базовый класс, т.е. метаклассом `cls` является `abc.ABCMeta`

=== Создание подкласса ABC

Важно воспользоваться уже существующим абстрактным классом. Потому что всё уже написано до нас.

Поэтому что бы реализовать колоду карт возьмём уже существующий `collections.MutableSequence`

[source, doctest]
----
Help on class MutableSequence in module collections.abc:
class MutableSequence(Sequence)
 |  All the operations on a read-write sequence.
 |
 |  Concrete subclasses must provide __new__ or __init__,
 |  __getitem__, __setitem__, __delitem__, __len__, and insert().
 |
 |  Порядок разрешения метода:
 |      MutableSequence
 |      Sequence
 |      Reversible
 |      Collection
 |      Sized
 |      Iterable
 |      Container
 |      builtins.object
 |
 |  Определенные здесь методы:
 |
 |  __delitem__(self, index)
 |
 |  __iadd__(self, values)
 |
 |  __setitem__(self, index, value)
 |
 |  append(self, value)
 |      S.append(value) -- append value to the end of the sequence
 |
 |  clear(self)
 |      S.clear() -> None -- remove all items from S
 |
 |  extend(self, values)
 |      S.extend(iterable) -- расширить последовательность, добавив элементы из повторяющегося
 |
 |  insert(self, index, value)
 |      S.insert(index, value) -- insert value before index
 |
 |  pop(self, index=-1)
 |      S.pop([index]) -> item -- remove and return item at index (default last).
 |      Raise IndexError if list is empty or index is out of range.
 |
 |  remove(self, value)
 |      S.remove(value) -- remove first occurrence of value.
 |      Raise ValueError if the value is not present.
 |
 |  reverse(self)
 |      S.reverse() -- reverse *IN PLACE*
 |
 |  ----------------------------------------------------------------------
 |  Данные и другие атрибуты, определенные здесь:
 |
 |  __abstractmethods__ = frozenset({'__delitem__', '__getitem__', '__len_...
 |
 |  ----------------------------------------------------------------------
 |  Методы, унаследованные от Sequence:
 |
 |  __contains__(self, value)
 |
 |  __getitem__(self, index)
 |
 |  __iter__(self)
 |
 |  __reversed__(self)
 |
 |  count(self, value)
 |      S.count(value) -> integer -- return number of occurrences of value
 |
 |  index(self, value, start=0, stop=None)
 |      S.index(value, [start, [stop]]) -> integer -- return first index of value.
 |      Raises ValueError if the value is not present.
 |
 |      Supporting start and stop arguments is optional, but
 |      recommended.
 |
 |  ----------------------------------------------------------------------
 |  Методы класса, унаследованные от Reversible:
 |
 |  __subclasshook__(C) from abc.ABCMeta
 |      Abstract classes can override this to customize issubclass().
 |
 |      This is invoked early on by abc.ABCMeta.__subclasscheck__().
 |      It should return True, False or NotImplemented.  If it returns
 |      NotImplemented, the normal algorithm is used.  Otherwise, it
 |      overrides the normal algorithm (and the outcome is cached).
 |
 |  ----------------------------------------------------------------------
 |  Методы, унаследованные от Sized:
 |
 |  __len__(self)
 |
 |  ----------------------------------------------------------------------
 |  Методы класса, унаследованные от Iterable:
 |
 |  __class_getitem__ = GenericAlias(...) from abc.ABCMeta
 |      Represent a PEP 585 generic type
 |
 |      E.g. for t = list[int], t.__origin__ is list and t.__args__ is (int,).
----

.*FrenchDeck2* подкласс `abc.MutableSequence`
[source, python]
----
include::{sourcedir}/frenchdeck2.py[]
----


TIP: На этапе импорта Python не проверяет, реализованы ли абстрактные методы. Это происходит только на этапе выполнения. И тогда если абстрактный метод не реализован, мы получим исключение `TypeError`. Поэтому мы обязаны реализовать `\\__delitem__` и `insert`, хотя они нам не нужны в примерах.


=== ABC в стандартной библиотеке

Большая часть ABC находятся в:

* `collections.abc`

* `numbers`

* `io`

==== Группы классов в модуле `collections.abc`:

* `Iterable`, `Container`, `Sized` -- Любая коллекция должна либо наследовать какому-то из этих ABC классов, либо реализовывать совместимые протоколы.

   - `Iterable` -- поддерживает итерирование методом `\\__iter__`

   - `Container` -- поддерживает оператор `in` методом `\\__contains__`

   - `Sized` -- поддерживает функцию `len()` методом `\\__len__`

* `Sequence`, `Mapping`, `Set` -- Это основные типы неизменяемых коллекций, и у каждого есть изменяемый подкласс.

* `MappingView` -- В Python3 объекты, возвращённые отображение метода `.items()`, `.keys()` и `.value()`, наследуют классы `ItemsView`, `KeysView` и `ValuesView()` соответственно. Первые 2 также наследуют богатый интерфейс класса `Set` со всеми операторами для работы над множествами.

* `Callable`, `Hashable` -- основное назначение - поддержка функций вызова и хеширования с помощью `isinstance`

* `Iterator` -- является подклассом `Iterable`

==== Числовая башня `numbers`

.В пакете `numbers` определена иерархия ABC, называемая "числовой башней"
[ditaa]
----
     +----------\
     | Numbers  |
  |  +----------+
  |  | Complex  |
  |  +----------+
  |  | Real     |
  |  +----------+
  |  | Rational |
  V  +----------+
     | Integral |
     \----------+
----

NOTE: Таким образом, если нужно проверить, является ли объект целым числом, вызывайте `isinstance(x, numbers.Integral)`. Этот метод вернёт `True` для типов `int`, `bool` и прочих целочисленных типов предоставленными внешними библиотеками, которые зарегистрируют свои типы как подклассы `abc` модуля `numbers`.

=== Определение и использование ABC

Пусть требуется отображать на сайте рекламные объявления в случайном порядке, но при этом не повторять никакое объявление, пока будут показаны все имеющиеся из набора.
Допустим мы разрабатываем рекламную систему под названием `ADAM`. Одно из требований -- поддержать предоставляемые пользователем классы случайного выбора без повторений. Что бы у пользователя не было сомнений, что понимается под "случайным выбором", мы определим ABC.

Наш ABC будет называться *Tombola* -- это итальянское название игры в Bingo.

В ABC `Tombola` определены 2 абстрактных метода:

- `.load(...)`: поместить элементы в контейнер

- `.pick()`: извлечь случайный элемент из коллекции и вернуть его.

И еще 2 конкретных метода:

- `.loaded()`: вернуть `True`, если в коллекции имеется хотя бы 1 элемент

- `.inspect()`: вернуть отсортированный кортеж `tuple`, составленный из элементов, находящихся в контейнере, не изменяя его содержимое. Внутреннее упорядочивание не сохраняется.

.Tombola - ABC с двумя абстрактными и двумя конкретными методами.
[source, python]
----
include::{sourcedir}/tombola.py[]
----

TIP: У абстрактного метода может существовать реализация. Но даже если так, подклассы все равно обязаны переопределить его, однако имеют право вызывать абстрактный метод через `super()`, расширяющего имеющуюся функциональность, вместо того, что бы реализовывать еге с нуля. Подробнее об использовании @abstractmethod кури мануал https://docs.python.org/3/library/abc.html[abc — Abstract Base Classes]


=== Синтаксические детали ABC

Лучший способ объявить ABC -- сделать его подклассом `abc.ABC` или какого-нибудь другого ABC. Однако `abc.ABC` появился только Python >= 3.4 и если используешь более раннюю версию то придется писать так: `class Tombola(metaclass=abc.ABCMeta)`.

.Именованный аргумент `metaclass=` был введён в Python 3. В Python 2 нужно было использовать атрибут класса `\\__metaclass__`:
[source, python]
----
class Tombols(object):  # Это для Python 2
    __metaclass__ = abc.ABCMeta
    # ...
----

В модуле `abc` так же есть и другие декораторы обозначающие методы класса и статические, но они избыточные, т.к. можно использовать несколько декораторов.

.Пример как объявлять абстрактный метод класса.
[source, python]
----
class MyABC(abc.ABC):

    @classmethod
    @abc.abstractmethod
    def an_abstract_classmethod(cls, ...)
        pass
----

WARNING: Порядок декораторов важен. Между `@abc.abstractmethod` и `def` не должно быть никаких других декораторов.

=== Создание подклассов ABC Tombola

[source, python]
----
include::{sourcedir}/bingo.py[]
----

[source, python]
----
include::{sourcedir}/lotto.py[]
----

[source, python]
----
include::{sourcedir}/tombolist.py[]
----

=== Использование метода `register` на практике

Чаще всего `register` можно использовать как функцию для регистрации классов, определённых где-то в другом месте.

=== Выводы

- *Интерфейсы* в духе протоколов не имеют ничего общего с наследованием; каждый класс реализует протокол независимо от остальных. Так выглядят интерфейсы в языках с динамической типизацией.

- Благодаря *гусиной типизации* абстрактные базовые классы (ABC) используются, чтобы сделать интерфейсы явными, а классы могут реализовывать интерфейсы либо с помощью наследования ABC, либо регистрации, для которой не требуется сильная статическая связь, характерная для наследования.

.Гусиная типизация
[quote, Alex Martelli, https://en.wikipedia.org/wiki/Duck_typing]
What goose typing means is: `isinstance(obj, cls)` is now just fine… as long as cls is an Abstract Base Class.

- Определение *абстрактного базового класса* позволяет зафиксировать общий API для множества подклассов. Эта возможность особенно полезна, когда человек, слабо знакомый с исходным кодом приложения, собирается написать для него подключаемый модуль. https://pymotw.com/3/abc/index.html#why-use-abstract-base-classes[Why use Abstract Base Classes?]

- `\\__subclasshook__` -- позволяет ABC распознавать незарегистрированные классы в качестве своего подкласса при условии, что он проходит некоторую проверку, которая может быть простой или сложной, как нужно разработчику,- классы из стандартной библиотеки всего лишь проверяют имена методов.

[quote, Luciano Ramalho]
Однажды поняв, что такое последовательность, мы можем применять это знание в разных контекстах. Это и есть главная тема моей книги: выявление фундаментальных идиом языка, что позволяет сделать код кратким, эффективным и удобочитаемым - для мастера-питониста.

