include::./.asciidoctor/.asciidoctorconfig[]

== Глава 14. Итерируемые объекты, итераторы и генераторы.

Итерирование -- одна из важнейших операций обработки данных. А если просматривается набор данных, не помещающийся целиком в память, то нужен способ выполнять её _отложенно_, т.е. по одному элементу и по запросу. Именно в этом смысл паттерна *Итератор*.

Ключевое слово *yield* (_появилось только в Py >= 2.2_) позволяет конструировать генераторы, которые работают как итераторы.

TIP: Любой генератор является итератором: генераторы используют весь интерфейс итераторов. Но итератор -- в том виде, как он определён в книге "Банды четырёх", -- извлекает элементы из коллекции, тогда как генератор может порождать элементы "из воздуха". Типичным примером является генератор чисел Фибоначчи -- бесконечно последовательности, которую нельзя сохранить в коллекции. Однако, надо иметь в виду, что в сообществе Python слова _итератор_ и _генератор_ обычно употребляется как синонимы.

=== Класс Sentence, попытка № 1: Последовательность слов.

В примере представлен класс `Sentence`, который умеет извлекать из текста слово с заданным индексом.

.`sentence.py`: объект `Sentence` как последовательность слов
[source, python]
----
include::{sourcedir}/sentence.py[]
----

Всякий раз когда интерпретатору нужно обойти объект `x`, он автоматически вызывает функцию `iter(x)`.

Встроенная функция `iter(x)` выполняет следующие действия.

1. Смотрим, реализует ли объект метод `\\__iter__`, и если да, вызывает его, что бы получить итератор.

2. Если метод `\\__iter__` не реализован, но реализован метод `\\__getitem__`, то Python создает итератор, который пытается извлекать элементы по порядку, начиная с индекса 0.

3. Если и это не получается, то возбуждает исключение -- обычно с сообщением `_C_ object is not iterable`, где _C_ -- класс объекта.

.`sentence_iter.py`:  класс `Sentence`, реализован с помощью паттерна Итератор
[source, python]
----
include::{sourcedir}/sentence_iter.py[]
----

.`sentence_gen.py`:  класс `Sentence`, реализован с помощью паттерна Генератора
[source, python]
----
include::{sourcedir}/sentence_gen.py[]
----


=== Как работает генераторная функция


NOTE: Любая функция Python, в теле которой встречается слово `yield`, называется генераторной функцией -- при вызове она возвращает объект-генератор.


.`sentence_gen2.py`:  класс `Sentence`, реализован с помощью паттерна Генератора
[source, python]
----
include::{sourcedir}/sentence_gen2.py[]
----