include::./.asciidoctor/.asciidoctorconfig[]

== Глава 13. Перезагрузка операторов как правильно?

=== Унарные операторы

 * `-`: `(\\__neg__)` -- Унарный арифметический минус.

 * `+`: `(\\__pos__)` -- Унарный арифметический плюс.

 * `~`: `(\\__invert__)` -- Поразраядная инверсия целого числа, определяется как ~x == -(x+1)

Поддерживать унарные операторы легко, достаточно переопределить один из специальных методов, который принимает только один аргумент `self` и возвращающий *новый* объект.

TIP: Специальные методы, реализующие унарные операторы или инфиксные операторы не должны изменять свои операнды.

.vector_v7.py: добавлены методы оператора `*`
[source, python]
----
include::{sourcedir}/vector_v7.py[]
----


.Имена методов инфиксных операторов
[cols="12,18,18,18,~"]
|===
^|Оператор ^|Прямой ^|Обратный ^|На месте ^|Описание

^|`+`
^|`\\__add__`
^|`\\__radd__`
^|`\\__iadd__`
|Сложение или конкатенация

^|`-`
^|`\\__sub__`
^|`\\__rsub__`
^|`\\__isub__`
|Вычитание

^|`*`
^|`\\__mul__`
^|`\\__rmul__`
^|`\\__imul__`
|Умножение, повторение


^|`/`
^|`\\__truediv__`
^|`\\__rtruediv__`
^|`\\__itruediv__`
|Истинное деление

^|`//`
^|`\\__floordiv__`
^|`\\__rfloordiv__`
^|`\\__ifloordiv__`
|Деление с округлением

^|`%`
^|`\\__mod__`
^|`\\__rmod__`
^|`\\__imod__`
|Деление по модулю

^|`divmod()`
^|`\\__divmod__`
^|`\\__rdivmod__`
^|`\\__idivmod__`
|Возвращает кортеж, содержащий частное и остаток

^|`**, pow()`
^|`\\__pow__`
^|`\\__rpow__`
^|`\\__ipow__`
|Возведение в степень

^|`@`
^|`\\__matmul__`
^|`\\__rmatmul__`
^|`\\__imatmul__`
|Матричное умножение (Py>=3.5) https://www.python.org/dev/peps/pep-0465/[PEP 465 -- A dedicated infix operator for matrix multiplication]

^|`&`
^|`\\__and__`
^|`\\__rand__`
^|`\\__iand__`
|Поразрядное *И*

^|`\|`
^|`\\__or__`
^|`\\__ror__`
^|`\\__ior__`
|Поразрядное *ИЛИ*

^|`^`
^|`\\__xor__`
^|`\\__rxor__`
^|`\\__ixor__`
|Поразрядное *ИСКЛЮЧАЮЩЕЕ ИЛИ*

^|`<<`
^|`\\__lshift__`
^|`\\__rlshift__`
^|`\\__ilshift__`
|Поразрядный сдвиг влево

^|`>>`
^|`\\__rshift__`
^|`\\__rrshift__`
^|`\\__irshift__`
|Поразрядный сдвиг вправо

|===

=== Операторы сравнения

Обработка операторов сравнения `==`, `!=`, `>`, `<`, `>=`, `\<=` интерпретатором Python похожа на то, что было выше, но имеет два важных отличия:

* Для прямых и инверсных вызовов служит один и тот же набор методов.

* В случае сравнения `==`, `!=`, если инверсный метод вызывает ошибку, то Python сравнивает идентификаторы объектов, а не возбуждает исключение `TypeError`

.Операторы сравнения: инверсные методы вызываются, когда первый вызов вернул `NotImplemented`
|===
^.^|Группа ^.^|Инфиксный оператор ^.^|Прямой вызов метода ^.^|Инверсный вызов метода ^.^|Запасной вариант

.2+^.^|Равенство
|`a == b`
|`a.\\__eq__(b)`
|`b.\\__eq__(a)`
|`return id(a) == id(b)`

|`a != b`
|`a.\\__ne__(b)`
|`b.\\__ne__(a)`
|`return not (a == b)`

.4+^.^|Порядок
|`a > b`
|`a.\\__gt__(b)`
|`a.\\__lt__(b)`
|`raise TypeError`

|`a < b`
|`a.\\__lt__(b)`
|`a.\\__gt__(b)`
|`raise TypeError`

|`a >= b`
|`a.\\__ge__(b)`
|`a.\\__le__(b)`
|`raise TypeError`

|`a <= b`
|`a.\\__le__(b)`
|`a.\\__ge__(b)`
|`raise TypeError`

|===

=== Операторы составного присваивания

Если в классе не реализован метод "на месте", то операторы составного сравнения не более чем синтаксическая глазурь: `a += b` вычисляется так же как `a = a + b`. Это ожидаемое поведение для неизменяемых типов и, если реализовать метод `\\__add__` то `+=` будет работать без всякого дополнительного кода.

Однако, если всё-таки реализовать метод оператора "на месте", например `\\__iadd__`, то он будет вызван для вычисления выражения `a += b`. Как следует из названия, такие операторы изменяют сам левый операнд, а не создают новый объект--результат.

CAUTION: Специальны методы, вычисляемые на месте, никогда не следует реализовывать для неизменяемых типов и, в частности, нашего класса `Vector`. Это в общем-то, очевидно, но лишний раз подчеркнуть не помешает.


